### ISSUE TITLE
Is there a way to handle Not Now in the Rate pop-up? from our own customisation?

### ISSUE THREAD

**Issue by RamkumarBPE** [KjellConnelly/react-native-rate#26]
Hi,
 Is it possible to handle Not Now(customise function) from the Rate pop up in iOS?

**Comment by KjellConnelly** [comment]
The iOS pop up is a SKStoreReviewController which only has a single function call with no parameters or return value. This means there is no way to customize the pop up, or what happens when they tap anything from within it. 

The only thing that I was able to customize was a hack to check if the pop up was displayed or not based on the number of window objects shown after a certain delay which only works for the first time you call it while the app is open. (Terminate app and reopen and it’ll work again). The readme has more info on this too.
