### ISSUE TITLE
Doesn't link for android platform.

### ISSUE THREAD

**Issue by heltleo** [KjellConnelly/react-native-rate#37]
Hi,

Thanks for awesome package first.

I'd like to use this platform on my RN project and was available to install this package via **yarn**.
When I try to link this package to platforms with **react-native link react-native-rate** command, it links to iOS platform, but doesn't link to Android platform at all.

React Native: v0.59.0
React: v16.8.3
react-native-rate: v1.0.9

There is no error during link process.
After link this package, I couldn't find android folder at the 'node_modules/react-native-rate'.

This is error I am facing when try to run on android.
![image](https://user-images.githubusercontent.com/42684441/61769097-cbea7100-ae1b-11e9-9025-9a55642b1853.png)

I spent a few days to find the solution, but couldn't find yet.

Thanks for any help.

**Comment by t0m0120** [comment]
@heltleo 
This package does not require an Android link

**Comment by harrisonschwartz** [comment]
Does the Android platform support in-app ratings like iOS does?

**Comment by heyman333** [comment]
@syntax-e no it doen't support As far as I know

**Comment by KjellConnelly** [comment]
This module doesn't support in-app ratings for Android. The google play store didn't support in-app ratings when I wrote this module a couple years ago. 

It is possible that Google Play does support this now, but I have no idea since I haven't done anything new to this module since then. If anyone knows, a pull request would be awesome :)
