### ISSUE TITLE
SKStoreReviewController not showing up in testflight 

### ISSUE THREAD

**Issue by MUllman** [KjellConnelly/react-native-rate#52]
Im not getting the SKStoreReviewController in testflight it is just going directly to the store. Locally I do see it, but in testflight (higher than ios 10.3) it just links to the store

**Comment by KjellConnelly** [comment]
This one is pretty obvious: https://developer.apple.com/documentation/storekit/skstorereviewcontroller/2851536-requestreview

Docs for SKStoreReviewController explicitly say that in development, the dialogue will show, but apps distributed via TestFlight do nothing. Since nothing occurs (ie another window isn't added to the stack), this module will open the App Store link (this behavior can be changed by looking at the README if you would prefer nothing to happen when a new window isn't added to the stack).
