### ISSUE TITLE
Can I able to show this as a like and its count value

### ISSUE THREAD

**Issue by nihp** [KjellConnelly/react-native-rate#53]
Can I able to show this rate as like and its count value (i.e) total liked count in react-native app

What are the options of rate. (Number, star, Heart etc ..)

Is it have that option.

Does it allow review for all values (If I did not set give the numerical value)

**Comment by KjellConnelly** [comment]
This module doesn't show any info like that, but there is a way to query for star ratings/reviews. I've done it for iOS apps at least. It invokes making a http request and getting back a JSON file. 

The other questions you have are mostly all questions about the App Store of choice. For example, the iOS App Store allows for 1-5 star ratings as well as reviews. 

I forget what the Google Play Store has since I don't use Android. 

The SKStoreReviewController allows for a 1-5 star rating in app, followed by an optional text review. All other options open the App Store of choice, meaning it's all their UI. The SKStoreReviewController is actually their UI as well, so you can't input any options there either.

**Comment by nihp** [comment]
@KjellConnelly I am using iOS app. Here I must need to use the SKStoreReviewController to review and write the apps

Also, Whether the SKStoreReviewController is mandatory one to write review the app?




> I forget what the Google Play Store has since I don't use Android.

I think it works for Android. Can you confirm does it work fine in android?

**Comment by nihp** [comment]
Also my question is If I set the preferInApp to false, where the popup will opens. Does it will opens in Appstore.

How the submit will happens after rating. How can i see the review screen in my simulator

**Comment by KjellConnelly** [comment]
I think most of the questions you're asking are already in the README file. But I'll try to answer again. 

SKStoreReviewController is an iOS only controller. If you set preferInApp to true, this module will try to use the SKStoreReviewController for iOS only. It has no effect on Android. Of course, there are conditions on this that are in the documentation, so if it fails, there is a way to make it open in the iOS App Store as a backup. 

If there is a way to review apps from within an Android app (instead of opening a link to the Google Play Store), it wasn't available when I first made this module, and thus, isn't a function of this app. 

If you use this module, it will always open in Google Play for Android which by a quick google search has stars as a way to review apps. Likes are not a thing. 

If you set preferInApp to false, it'll open the App Store app on iOS, and Google Play for Android (unless of course you're using Amazon)

**Comment by nihp** [comment]
Thanks for your clarification.

I have implemented this, here If I click submit in my simulator it not makes any action.

Here after success rated, shall I need to give navigation url? 

Or how can I verify it in simulator?
