### ISSUE TITLE
App Store Opens after the InApp shows

### ISSUE THREAD

**Issue by Diego-Franco** [KjellConnelly/react-native-rate#7]
Device: iPhone SE
OS: 11.0.1

When I use this options:
const options = {
	AppleAppID: '123456',
	GooglePackageName: 'com.example.app',
	preferInApp: true,
};

the App Store open after 3 seconds and is ok is how the documentations says, if I try to use inAppDelay: 10.0 the AppStore opens after 10, but if the inApp prompt showed and dismissed the AppStore is open anyways.

**Comment by KjellConnelly** [comment]
Hi Diego,

This is expected behavior because the hack I wrote works by checking if there is another window open on top of your app after 3.0s, or in your case, 10.0s. Unfortunately, Apple never gives a callback for failure, so this is the best I could do. I wouldn’t set the delay to 10s because most users will dismiss the pop up before then. Think about how much time a user would need to recognize that it is asking for a rating and make a decision. 10s is too long. In a production case, I would probably do 3s or less. Maybe even 1s.
